linters:
    Indentation:
        enabled: true
        width: 4

    ColorKeyword:
        enabled: false

    PlaceholderInExtend:
        enabled: false

    SpaceAfterComma:
        enabled: false